# Generated by Django 2.2.7 on 2019-12-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=64)),
                ('l_name', models.CharField(max_length=64)),
                ('hotel_name', models.CharField(max_length=64)),
                ('d_num', models.CharField(max_length=64)),
                ('d_adrr', models.CharField(max_length=64)),
                ('d_adhaar', models.CharField(max_length=64)),
                ('pword', models.CharField(max_length=64)),
                ('d_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGO_name', models.CharField(max_length=64)),
                ('NGO_num', models.CharField(max_length=10)),
                ('NGO_adrr', models.CharField(max_length=64)),
                ('NGO_adhaar', models.CharField(max_length=16)),
                ('pword', models.CharField(max_length=64)),
                ('NGO_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=64)),
                ('l_name', models.CharField(max_length=64)),
                ('v_num', models.CharField(max_length=64)),
                ('v_adrr', models.CharField(max_length=64)),
                ('v_adhaar', models.CharField(max_length=64)),
                ('pword', models.CharField(max_length=64)),
                ('v_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=64)),
                ('food_qty', models.CharField(max_length=64)),
                ('ngo_id', models.CharField(max_length=64, null=True)),
                ('donor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Donor')),
                ('volunteer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Volunteer')),
            ],
        ),
    ]
